name: fieldx_fsm
description: "A new Flutter project."
publish_to: 'none'
version: 3.3.3+12

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.5.1
  google_sign_in: ^7.0.0
  mobile_scanner: ^7.0.1
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  fl_chart: ^1.0.0
  material_design_icons_flutter: ^7.0.7296
  file_picker: ^10.1.2
  mime: ^2.0.0
  flutter_osm_plugin: ^1.3.6
  connectivity_plus: ^6.1.3
  flutter_html: 3.0.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  awesome_notifications: 0.10.1
  geolocator: ^14.0.0
  weather: ^3.2.1
  table_calendar: ^3.2.0
  flutter_cache_manager: ^3.4.1
  excel: ^4.0.6
  flutter_secure_storage: ^9.2.4
  web_socket_channel: ^3.0.3
  package_info_plus: 8.3.0
  device_info_plus: ^11.5.0
  signature: ^6.3.0
  pdf: ^3.10.4
  printing: ^5.11.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  dio: ^5.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # For unit testing and packages_autoroller support
  test: ^1.24.0
  process: 5.0.4
  args: ^2.4.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - .env
